name: Build and Deploy UI Bundle

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set Git Identity
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 3: Create the zip file
      - name: Zip the UI bundle
        run: |
          mkdir -p build
          zip -r build/ui-bundle.zip ./*

      # Step 4: Switch to the 'bundle' branch
      - name: Checkout or Create Bundle Branch
        run: |
          git fetch origin bundle || echo "No existing bundle branch"
          git checkout -B bundle

      # Step 5: Clear the branch and add the zip file
      - name: Clear Branch and Add Zip
        run: |
          rm -rf *
          mv build/ui-bundle.zip .
          git add ui-bundle.zip

      # Step 6: Commit and Push Changes
      - name: Commit and Push
        run: |
          git commit -m "Update UI bundle on push to main" || echo "No changes to commit"
          git push origin bundle --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
