name: Build and Publish UI Bundle to Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set Git Identity
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 3: Create the zip file
      - name: Create UI Bundle
        run: |
          mkdir -p build
          zip -r build/ui-bundle.zip ./*

      # Step 4: Create a Git Tag
      - name: Create Git Tag
        id: create_tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          git tag $TAG_NAME
          git push origin $TAG_NAME

      # Step 5: Create a Release and Upload the Bundle
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/ui-bundle.zip
          tag_name: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
